module.exports = {
  inputFiles: ["./src/http.ts", "./src/result.ts"],
  out: "docs",
  excludeExternals: true,
  excludeNotExported: true,
  externalPattern: ["**/__tests__/**", "**/__examples__/**", "**/index.ts"],
  // theme: "minimal",
  categorizeByGroup: false,
  categoryOrder: [
    "Effect Manager",
    "Requests",
    "Header",
    "Body",
    "Body Parts",
    "Expect",
    "Progress",
    "Cancel",
    "Risky Requests",
    "Elaborate Expectations",
    "*",
  ],
};
